### ISSUE TITLE
运行docker版本报 “not found xt_TPROXY.ko” 错误

### ISSUE THREAD

**Issue by tom-snow** [NavyD/docker-clash#1]
另外在 debian 系统上运行也会有类似错误，原因应该是是在读取 “/proc/sys/kernel/osrelease” 文件时会多出一个换行符，导致后续遍历目录时使用的路径不正确，解决方法是修改 `clashutil/clash.py` 文件第 256 行
```python
    def __check_tproxy_mod(self):
         path = "/lib/modules/{}".format(
             Path("/proc/sys/kernel/osrelease").read_text()).strip() # line:256, 使用 strip() 函数去除路径末尾的换行符
         self.log.debug(f"checking if the tproxy module exists in path {path}")
         for _, _, files in walk(path, followlinks=True):
             for name in files:
```

做以上修改后在 debian 系统的 docker 中运行仍会报错，我个人是加了判断是否在 docker 环境中（判断 `/.dockerenv` 是否存在），若 docker 中就跳过检查，然后就可以正常使用 clash 了，但不清楚这个 `xt_TPROXY.ko` 文件具体有什么用，不知道这样改会有什么影响，就没提交修改

**Comment by NavyD** [comment]
xt_TPROXY.ko用于在linux下使用iptables配置tcp udp转发redir的模块，如果clash配置了tun模式，则不会检查xt_TPROXY.ko文件的

我这没有debian环境，如果你有更好的想法，欢迎提交

**Comment by tom-snow** [comment]
你在你环境下使用 docker 镜像不用 tun 模式会不会也报  “not found xt_TPROXY.ko” 的错误呢
如果也会报的话可以考虑在那个 __check_tproxy_mod()  function 上加上检查是否在 docker 环境，是就跳过检查。然后 ReadMe 上注明一下让不使用 tun 模式的 docker 用户注意检查一下是否存在那个依赖应该就好

**Comment by NavyD** [comment]
异常就是提醒用户的，在我这是可以正常使用的，稍后我修改下readme

另外，在WSL环境下是没有TPROXY模块的哈，一般正常的发行版都没有裁剪 TPROXY 模块，TPROXY 模块缺失问题主要出现在无线路由固件上（某些精简型发行版也会去掉 TPROXY 模块，比如 Alpine）。

使用以下方法可以检测当前内核是否包含 TPROXY 模块。

```bash
# 查找 TPROXY 模块
$ find /lib/modules/$(uname -r) -type f -name 'xt_TPROXY.ko*'
# 正常情况下的输出
/lib/modules/4.16.8-1-ARCH/kernel/net/netfilter/xt_TPROXY.ko.xz
```

参考：

* [View Linux Kernel Config Options [closed]](https://stackoverflow.com/a/14382864/8566831)
* [记一次在suse上遇到的TPROXY的坑。](https://www.jianshu.com/p/9a1909bcc54f)
* [linux系统管理（1）之 内核编译选项查看](https://www.cnblogs.com/linengier/p/9956517.html)
* [Where are the current kernel build options stored?](https://unix.stackexchange.com/a/83327)
* [Linux 透明代理 tproxy](https://github.com/zfl9/ss-tproxy/wiki/Linux-%E9%80%8F%E6%98%8E%E4%BB%A3%E7%90%86#tproxy)
